# # Navy Blue Gradient
# [theme]
# primaryColor="#9db2bf"
# backgroundColor="#27374d"
# secondaryBackgroundColor="#526d82"
# textColor="#f5f5fb"

# # Dark Blue
# [theme]
# primaryColor="#00adb5"
# backgroundColor="#222831"
# secondaryBackgroundColor="#393e46"
# textColor="#eeeeee"


# # Light Beige x Orange
# [theme]
# primaryColor="#F37A1F"
# backgroundColor="#D0D0C4"
# secondaryBackgroundColor="#D0D0C4"
# textColor="#393939"


# Light Grey x Blue
[theme]
primaryColor="#3e61e3"
backgroundColor="#f1eef0"
secondaryBackgroundColor="#e6e6e6"
textColor="#000000"
headerColor="#C2492F"


# # Light Grey x Red
# [theme]
# primaryColor="#CD0D32"
# backgroundColor="#E1DFE4"
# secondaryBackgroundColor="#dedce3"
# textColor="#727272"

# # Retro
# [theme]
# primaryColor="#EA5455"
# backgroundColor="#F9F5EB"
# secondaryBackgroundColor="#E4DCCF"
# textColor="#002B5B"
# headerColor="#EA5455"