# # Slate
# [theme]
# primaryColor="#3e61e3"
# backgroundColor="#f1eef0"
# secondaryBackgroundColor="#e6e6e6"
# textColor="#000000"
# headerColor="#C2492F"


# Retro
[theme]
primaryColor="#3e61e3"
backgroundColor="#F9F5EB"
secondaryBackgroundColor="#E4DCCF"
textColor="#002B5B"
headerColor="#EA5455"

# Bright
# [theme]
# primaryColor="#F64C72"
# backgroundColor="#2F2FA2"
# secondaryBackgroundColor="#242582"
# textColor="#FFFFFF"
# headerColor="#F64C72"

# # Minimal
# [theme]
# primaryColor="#000000"
# backgroundColor="#FFFFFF"
# secondaryBackgroundColor="#FFFFFF"
# textColor="#000000"

[client]
toolbarMode="minimal"